apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: renovate-bot
  namespace: tekton-resources
  labels:
    app.kubernetes.io/version: '0.1'
spec:
  description: >-
    This task runs the renovate bot
  params:
    - default: test
      description: The secret name to use
      name: api_token_secret_name
      type: string
    - default: renovate/renovate
      description: The secret name to use
      name: renovate_image_name
      type: string
  steps:
    - env:
        - name: "TOKEN"
          valueFrom:
            secretKeyRef:
              key: "token"
              name: "api-token-secret"
      image: $(params.renovate_image_name)
      name: renovate
      resources: {}
      script: |
        #!/usr/bin/env bash
        echo $TOKEN
