apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: renovate-
  namespace: tekton-resources
spec:
  taskRef:
    resolver: cluster
    params:
      - name: kind
        value: task
      - name: name
        value: renovate-bot
      - name: namespace
        value: tekton-resources
  params:
  - name: api_token_secret_name
    value: git@github.com:andifg/react-pipeline-test-application.git
