apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: renovate-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: trigger-renovate
      template:
        ref: renovate-task