apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: renovate-task
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: renovate-
      namespace: renovate-bot
    spec:
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/andifg/renovate-tekton-task.git
          - name: revision
            value: main
          - name: pathInRepo
            value: renovate/0.1/task.yaml
      params:
      - name: renovate-platform
        value: github
      - name: renovate-token-secret-name
        value: renovate-api-token-github
      - name: renovate-repositories
        value: '["andifg/email_rule_engine", "andifg/coffee_backend"]'
      workspaces:
        - name: renovate-base-dir-cache
          persistentVolumeClaim:
            claimName: renovate-cache