kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: renovate-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem